import type { Metadata } from "next";
import { Navbar } from "@components/Navbar/Navbar";
import { Footer } from "@/components/Footer/Footer";
import "./globals.css";
import dynamic from "next/dynamic";
import { ComponentType } from "react";

export const metadata: Metadata = {
  title: "User app",
  description: "Generated by create next app",
};

const DynamicThemeController: ComponentType<{}> = dynamic(
  () =>
    import("../components/ThemeController/ThemeController").then(
      (mod) => mod.default
    ),
  {
    ssr: false,
  }
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <DynamicThemeController />
        <main className="container mx-auto mt-5 mb-10 min-h-[calc(80vh-5rem)] flex justify-center items-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
